### ISSUE TITLE
unable to patch the openfst.patch

### ISSUE THREAD

**Issue by sdabuk** [jasperproject/jasper-client#104]
HI, 
I am using Ubuntu 12.04. I want to use KALDI toolkit for my project. I am unable to install the OpenFST under kaldi-trunk/tools. I am using the install instructions in kaldi-trunk/tools/INSTALL. 

I already have make "make -j 4" and install sph2pipe. Now i need to install openFST. 

I am using terminal and I have completed the steps till here:
wget http://openfst.cs.nyu.edu/twiki/pub/FST/FstDownload/openfst-1.3.2.tar.gz
tar -xovzf openfst-1.3.2.tar.gz  

But, I am unable to patch the openfst.patch. Kindly help me in this regard. I am new to this toolkit. 
Do I need to patch it after the compilation of openFST in terminal or I need to patch it before? and how do I need to patch the file openFST.patch?  It is available in Kaldi-trunk/tools.  

Thank you.

**Comment by pawan191994** [comment]
I have the same problem what is the command to patch and which file we have to patch.
I am using instructions given in install file it says that run command 
>> for dir in openfst-1.3.2/{src/,}include/fst; do     ( [ -d $dir ] && cd $dir && patch -p0 -N <../../../../openfst.patch ) ; done
but it give me following error
bash: ../../../../openfst.patch: No such file or directory

**Comment by pawan191994** [comment]
Please give me a solution i am stuck..!!

**Comment by roozbehsadeghian** [comment]
@pawan191994  That might be because of pulling the newer version of kaldi which is prepared for openfst-1.3.4. So you don't have the openfst.patch, instead you have **openfst-1.3.4**.patch. Try to address to this folder. It is under tools/extras or simply copy it to wherever you want.

> I have the same problem what is the command to patch and which file we have to patch.
I am using instructions given in install file it says that run command

for dir in openfst-1.3.2/{src/,}include/fst; do ( [ -d $dir ] && cd $dir && patch -p0 -N <../../../../openfst.patch ) ; done
but it give me following error
bash: ../../../../openfst.patch: No such file or directory
