### ISSUE TITLE
Q: Will the new plugin system allow for multiple mics?

### ISSUE THREAD

**Issue by redfast00** [jasperproject/jasper-client#395]
I currently have a usb hub and 10 usb sound cards. I am planning to automate my house using Jasper and 10 mics. Will this be possible with the new plugin system? Will a plugin be able to see from which mic a command is detected? Thanks

**Comment by Holzhaus** [comment]
Maybe. Not sure yet if we want this. since it would imply heave threading and makes the codebase a lot more complex. Anyhow, you can still archieve the same with the current `jasper-dev` branch by adding multiple users and configuring different soundcards in their individual `~/.jasper/profile.yml` files.

**Comment by redfast00** [comment]
Would I also be able to archieve the same if I mix multiple microphones? (No idea how I would do that...) If I run multiple Jasper's at the same time, will they conflict?

**Comment by Holzhaus** [comment]
If the distance between the mics is big enough, it shouldn't conflict. If you envounter any bug, feel free to report it.
